haldevice.o: haldevice.cpp haldebug.h ../common/debug.h haldevice.h \
  ../cbus/cbus.h ../cbus/cbusobject.h ../cbus/cbusfilter.h \
  /usr/include/sigc++-2.0/sigc++/sigc++.h \
  /usr/include/sigc++-2.0/sigc++/signal.h \
  /usr/include/sigc++-2.0/sigc++/signal_base.h \
  /usr/lib/sigc++-2.0/include/sigc++config.h \
  /usr/include/sigc++-2.0/sigc++/type_traits.h \
  /usr/include/sigc++-2.0/sigc++/reference_wrapper.h \
  /usr/include/sigc++-2.0/sigc++/trackable.h \
  /usr/include/sigc++-2.0/sigc++/functors/slot.h \
  /usr/include/sigc++-2.0/sigc++/visit_each.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/adaptor_trait.h \
  /usr/include/sigc++-2.0/sigc++/functors/functor_trait.h \
  /usr/include/sigc++-2.0/sigc++/functors/ptr_fun.h \
  /usr/include/sigc++-2.0/sigc++/functors/mem_fun.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/deduce_result_type.h \
  /usr/include/sigc++-2.0/sigc++/functors/slot_base.h \
  /usr/include/sigc++-2.0/sigc++/connection.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/adaptors.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/bind.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/bind_return.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/hide.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/retype_return.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/retype.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/compose.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/exception_catch.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/lambda.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/base.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/select.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/operator.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/group.h \
  /usr/include/sigc++-2.0/sigc++/functors/functors.h \
  /usr/include/dbus-1.0/dbus/dbus.h \
  /usr/lib/dbus-1.0/include/dbus/dbus-arch-deps.h \
  /usr/include/dbus-1.0/dbus/dbus-macros.h \
  /usr/include/dbus-1.0/dbus/dbus-address.h \
  /usr/include/dbus-1.0/dbus/dbus-types.h \
  /usr/include/dbus-1.0/dbus/dbus-errors.h \
  /usr/include/dbus-1.0/dbus/dbus-bus.h \
  /usr/include/dbus-1.0/dbus/dbus-connection.h \
  /usr/include/dbus-1.0/dbus/dbus-memory.h \
  /usr/include/dbus-1.0/dbus/dbus-message.h \
  /usr/include/dbus-1.0/dbus/dbus-shared.h \
  /usr/include/dbus-1.0/dbus/dbus-pending-call.h \
  /usr/include/dbus-1.0/dbus/dbus-protocol.h \
  /usr/include/dbus-1.0/dbus/dbus-server.h \
  /usr/include/dbus-1.0/dbus/dbus-threads.h ../cbus/cbusconnection.h \
  ../cbus/cbusmonitor.h ../cbus/../common/fdnotifier.h \
  ../cbus/../common/timeout.h ../cbus/cbuserror.h ../cbus/cbusmessage.h \
  ../cbus/cbuspendingcall.h ../cbus/cbusinterface.h ../cbus/cbusserver.h \
  ../cbus/../common/eventloop.h
halmanager.o: halmanager.cpp haldebug.h ../common/debug.h halmanager.h \
  ../cbus/cbus.h ../cbus/cbusobject.h ../cbus/cbusfilter.h \
  /usr/include/sigc++-2.0/sigc++/sigc++.h \
  /usr/include/sigc++-2.0/sigc++/signal.h \
  /usr/include/sigc++-2.0/sigc++/signal_base.h \
  /usr/lib/sigc++-2.0/include/sigc++config.h \
  /usr/include/sigc++-2.0/sigc++/type_traits.h \
  /usr/include/sigc++-2.0/sigc++/reference_wrapper.h \
  /usr/include/sigc++-2.0/sigc++/trackable.h \
  /usr/include/sigc++-2.0/sigc++/functors/slot.h \
  /usr/include/sigc++-2.0/sigc++/visit_each.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/adaptor_trait.h \
  /usr/include/sigc++-2.0/sigc++/functors/functor_trait.h \
  /usr/include/sigc++-2.0/sigc++/functors/ptr_fun.h \
  /usr/include/sigc++-2.0/sigc++/functors/mem_fun.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/deduce_result_type.h \
  /usr/include/sigc++-2.0/sigc++/functors/slot_base.h \
  /usr/include/sigc++-2.0/sigc++/connection.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/adaptors.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/bind.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/bind_return.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/hide.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/retype_return.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/retype.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/compose.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/exception_catch.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/lambda.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/base.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/select.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/operator.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/group.h \
  /usr/include/sigc++-2.0/sigc++/functors/functors.h \
  /usr/include/dbus-1.0/dbus/dbus.h \
  /usr/lib/dbus-1.0/include/dbus/dbus-arch-deps.h \
  /usr/include/dbus-1.0/dbus/dbus-macros.h \
  /usr/include/dbus-1.0/dbus/dbus-address.h \
  /usr/include/dbus-1.0/dbus/dbus-types.h \
  /usr/include/dbus-1.0/dbus/dbus-errors.h \
  /usr/include/dbus-1.0/dbus/dbus-bus.h \
  /usr/include/dbus-1.0/dbus/dbus-connection.h \
  /usr/include/dbus-1.0/dbus/dbus-memory.h \
  /usr/include/dbus-1.0/dbus/dbus-message.h \
  /usr/include/dbus-1.0/dbus/dbus-shared.h \
  /usr/include/dbus-1.0/dbus/dbus-pending-call.h \
  /usr/include/dbus-1.0/dbus/dbus-protocol.h \
  /usr/include/dbus-1.0/dbus/dbus-server.h \
  /usr/include/dbus-1.0/dbus/dbus-threads.h ../cbus/cbusconnection.h \
  ../cbus/cbusmonitor.h ../cbus/../common/fdnotifier.h \
  ../cbus/../common/timeout.h ../cbus/cbuserror.h ../cbus/cbusmessage.h \
  ../cbus/cbuspendingcall.h ../cbus/cbusinterface.h ../cbus/cbusserver.h \
  ../cbus/../common/eventloop.h haldevice.h
eventloop.o: ../common/eventloop.cpp ../common/debug.h \
  ../common/eventloop.h ../common/timeout.h \
  /usr/include/sigc++-2.0/sigc++/sigc++.h \
  /usr/include/sigc++-2.0/sigc++/signal.h \
  /usr/include/sigc++-2.0/sigc++/signal_base.h \
  /usr/lib/sigc++-2.0/include/sigc++config.h \
  /usr/include/sigc++-2.0/sigc++/type_traits.h \
  /usr/include/sigc++-2.0/sigc++/reference_wrapper.h \
  /usr/include/sigc++-2.0/sigc++/trackable.h \
  /usr/include/sigc++-2.0/sigc++/functors/slot.h \
  /usr/include/sigc++-2.0/sigc++/visit_each.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/adaptor_trait.h \
  /usr/include/sigc++-2.0/sigc++/functors/functor_trait.h \
  /usr/include/sigc++-2.0/sigc++/functors/ptr_fun.h \
  /usr/include/sigc++-2.0/sigc++/functors/mem_fun.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/deduce_result_type.h \
  /usr/include/sigc++-2.0/sigc++/functors/slot_base.h \
  /usr/include/sigc++-2.0/sigc++/connection.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/adaptors.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/bind.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/bind_return.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/hide.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/retype_return.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/retype.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/compose.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/exception_catch.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/lambda.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/base.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/select.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/operator.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/group.h \
  /usr/include/sigc++-2.0/sigc++/functors/functors.h \
  ../common/fdnotifier.h
fdnotifier.o: ../common/fdnotifier.cpp ../common/fdnotifier.h \
  /usr/include/sigc++-2.0/sigc++/sigc++.h \
  /usr/include/sigc++-2.0/sigc++/signal.h \
  /usr/include/sigc++-2.0/sigc++/signal_base.h \
  /usr/lib/sigc++-2.0/include/sigc++config.h \
  /usr/include/sigc++-2.0/sigc++/type_traits.h \
  /usr/include/sigc++-2.0/sigc++/reference_wrapper.h \
  /usr/include/sigc++-2.0/sigc++/trackable.h \
  /usr/include/sigc++-2.0/sigc++/functors/slot.h \
  /usr/include/sigc++-2.0/sigc++/visit_each.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/adaptor_trait.h \
  /usr/include/sigc++-2.0/sigc++/functors/functor_trait.h \
  /usr/include/sigc++-2.0/sigc++/functors/ptr_fun.h \
  /usr/include/sigc++-2.0/sigc++/functors/mem_fun.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/deduce_result_type.h \
  /usr/include/sigc++-2.0/sigc++/functors/slot_base.h \
  /usr/include/sigc++-2.0/sigc++/connection.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/adaptors.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/bind.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/bind_return.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/hide.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/retype_return.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/retype.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/compose.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/exception_catch.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/lambda.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/base.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/select.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/operator.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/group.h \
  /usr/include/sigc++-2.0/sigc++/functors/functors.h
timeout.o: ../common/timeout.cpp ../common/timeout.h \
  /usr/include/sigc++-2.0/sigc++/sigc++.h \
  /usr/include/sigc++-2.0/sigc++/signal.h \
  /usr/include/sigc++-2.0/sigc++/signal_base.h \
  /usr/lib/sigc++-2.0/include/sigc++config.h \
  /usr/include/sigc++-2.0/sigc++/type_traits.h \
  /usr/include/sigc++-2.0/sigc++/reference_wrapper.h \
  /usr/include/sigc++-2.0/sigc++/trackable.h \
  /usr/include/sigc++-2.0/sigc++/functors/slot.h \
  /usr/include/sigc++-2.0/sigc++/visit_each.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/adaptor_trait.h \
  /usr/include/sigc++-2.0/sigc++/functors/functor_trait.h \
  /usr/include/sigc++-2.0/sigc++/functors/ptr_fun.h \
  /usr/include/sigc++-2.0/sigc++/functors/mem_fun.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/deduce_result_type.h \
  /usr/include/sigc++-2.0/sigc++/functors/slot_base.h \
  /usr/include/sigc++-2.0/sigc++/connection.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/adaptors.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/bind.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/bind_return.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/hide.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/retype_return.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/retype.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/compose.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/exception_catch.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/lambda.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/base.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/select.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/operator.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/group.h \
  /usr/include/sigc++-2.0/sigc++/functors/functors.h
cbusconnection.o: ../cbus/cbusconnection.cpp ../cbus/cbusdebug.h \
  ../cbus/../common/debug.h ../cbus/cbusconnection.h \
  /usr/include/dbus-1.0/dbus/dbus.h \
  /usr/lib/dbus-1.0/include/dbus/dbus-arch-deps.h \
  /usr/include/dbus-1.0/dbus/dbus-macros.h \
  /usr/include/dbus-1.0/dbus/dbus-address.h \
  /usr/include/dbus-1.0/dbus/dbus-types.h \
  /usr/include/dbus-1.0/dbus/dbus-errors.h \
  /usr/include/dbus-1.0/dbus/dbus-bus.h \
  /usr/include/dbus-1.0/dbus/dbus-connection.h \
  /usr/include/dbus-1.0/dbus/dbus-memory.h \
  /usr/include/dbus-1.0/dbus/dbus-message.h \
  /usr/include/dbus-1.0/dbus/dbus-shared.h \
  /usr/include/dbus-1.0/dbus/dbus-pending-call.h \
  /usr/include/dbus-1.0/dbus/dbus-protocol.h \
  /usr/include/dbus-1.0/dbus/dbus-server.h \
  /usr/include/dbus-1.0/dbus/dbus-threads.h ../cbus/cbusmonitor.h \
  ../cbus/../common/fdnotifier.h /usr/include/sigc++-2.0/sigc++/sigc++.h \
  /usr/include/sigc++-2.0/sigc++/signal.h \
  /usr/include/sigc++-2.0/sigc++/signal_base.h \
  /usr/lib/sigc++-2.0/include/sigc++config.h \
  /usr/include/sigc++-2.0/sigc++/type_traits.h \
  /usr/include/sigc++-2.0/sigc++/reference_wrapper.h \
  /usr/include/sigc++-2.0/sigc++/trackable.h \
  /usr/include/sigc++-2.0/sigc++/functors/slot.h \
  /usr/include/sigc++-2.0/sigc++/visit_each.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/adaptor_trait.h \
  /usr/include/sigc++-2.0/sigc++/functors/functor_trait.h \
  /usr/include/sigc++-2.0/sigc++/functors/ptr_fun.h \
  /usr/include/sigc++-2.0/sigc++/functors/mem_fun.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/deduce_result_type.h \
  /usr/include/sigc++-2.0/sigc++/functors/slot_base.h \
  /usr/include/sigc++-2.0/sigc++/connection.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/adaptors.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/bind.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/bind_return.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/hide.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/retype_return.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/retype.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/compose.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/exception_catch.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/lambda.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/base.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/select.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/operator.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/group.h \
  /usr/include/sigc++-2.0/sigc++/functors/functors.h \
  ../cbus/../common/timeout.h ../cbus/cbuserror.h ../cbus/cbusmessage.h \
  ../cbus/cbuspendingcall.h ../cbus/cbusfilter.h
cbuserror.o: ../cbus/cbuserror.cpp ../cbus/cbusdebug.h \
  ../cbus/../common/debug.h ../cbus/cbuserror.h \
  /usr/include/dbus-1.0/dbus/dbus.h \
  /usr/lib/dbus-1.0/include/dbus/dbus-arch-deps.h \
  /usr/include/dbus-1.0/dbus/dbus-macros.h \
  /usr/include/dbus-1.0/dbus/dbus-address.h \
  /usr/include/dbus-1.0/dbus/dbus-types.h \
  /usr/include/dbus-1.0/dbus/dbus-errors.h \
  /usr/include/dbus-1.0/dbus/dbus-bus.h \
  /usr/include/dbus-1.0/dbus/dbus-connection.h \
  /usr/include/dbus-1.0/dbus/dbus-memory.h \
  /usr/include/dbus-1.0/dbus/dbus-message.h \
  /usr/include/dbus-1.0/dbus/dbus-shared.h \
  /usr/include/dbus-1.0/dbus/dbus-pending-call.h \
  /usr/include/dbus-1.0/dbus/dbus-protocol.h \
  /usr/include/dbus-1.0/dbus/dbus-server.h \
  /usr/include/dbus-1.0/dbus/dbus-threads.h ../cbus/cbusmessage.h \
  ../cbus/cbusconnection.h ../cbus/cbusmonitor.h \
  ../cbus/../common/fdnotifier.h /usr/include/sigc++-2.0/sigc++/sigc++.h \
  /usr/include/sigc++-2.0/sigc++/signal.h \
  /usr/include/sigc++-2.0/sigc++/signal_base.h \
  /usr/lib/sigc++-2.0/include/sigc++config.h \
  /usr/include/sigc++-2.0/sigc++/type_traits.h \
  /usr/include/sigc++-2.0/sigc++/reference_wrapper.h \
  /usr/include/sigc++-2.0/sigc++/trackable.h \
  /usr/include/sigc++-2.0/sigc++/functors/slot.h \
  /usr/include/sigc++-2.0/sigc++/visit_each.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/adaptor_trait.h \
  /usr/include/sigc++-2.0/sigc++/functors/functor_trait.h \
  /usr/include/sigc++-2.0/sigc++/functors/ptr_fun.h \
  /usr/include/sigc++-2.0/sigc++/functors/mem_fun.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/deduce_result_type.h \
  /usr/include/sigc++-2.0/sigc++/functors/slot_base.h \
  /usr/include/sigc++-2.0/sigc++/connection.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/adaptors.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/bind.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/bind_return.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/hide.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/retype_return.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/retype.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/compose.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/exception_catch.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/lambda.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/base.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/select.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/operator.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/group.h \
  /usr/include/sigc++-2.0/sigc++/functors/functors.h \
  ../cbus/../common/timeout.h ../cbus/cbuspendingcall.h \
  ../cbus/cbusfilter.h
cbusinterface.o: ../cbus/cbusinterface.cpp ../cbus/cbusdebug.h \
  ../cbus/../common/debug.h ../cbus/cbusinterface.h \
  /usr/include/sigc++-2.0/sigc++/sigc++.h \
  /usr/include/sigc++-2.0/sigc++/signal.h \
  /usr/include/sigc++-2.0/sigc++/signal_base.h \
  /usr/lib/sigc++-2.0/include/sigc++config.h \
  /usr/include/sigc++-2.0/sigc++/type_traits.h \
  /usr/include/sigc++-2.0/sigc++/reference_wrapper.h \
  /usr/include/sigc++-2.0/sigc++/trackable.h \
  /usr/include/sigc++-2.0/sigc++/functors/slot.h \
  /usr/include/sigc++-2.0/sigc++/visit_each.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/adaptor_trait.h \
  /usr/include/sigc++-2.0/sigc++/functors/functor_trait.h \
  /usr/include/sigc++-2.0/sigc++/functors/ptr_fun.h \
  /usr/include/sigc++-2.0/sigc++/functors/mem_fun.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/deduce_result_type.h \
  /usr/include/sigc++-2.0/sigc++/functors/slot_base.h \
  /usr/include/sigc++-2.0/sigc++/connection.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/adaptors.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/bind.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/bind_return.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/hide.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/retype_return.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/retype.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/compose.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/exception_catch.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/lambda.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/base.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/select.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/operator.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/group.h \
  /usr/include/sigc++-2.0/sigc++/functors/functors.h ../cbus/cbusobject.h \
  ../cbus/cbusfilter.h /usr/include/dbus-1.0/dbus/dbus.h \
  /usr/lib/dbus-1.0/include/dbus/dbus-arch-deps.h \
  /usr/include/dbus-1.0/dbus/dbus-macros.h \
  /usr/include/dbus-1.0/dbus/dbus-address.h \
  /usr/include/dbus-1.0/dbus/dbus-types.h \
  /usr/include/dbus-1.0/dbus/dbus-errors.h \
  /usr/include/dbus-1.0/dbus/dbus-bus.h \
  /usr/include/dbus-1.0/dbus/dbus-connection.h \
  /usr/include/dbus-1.0/dbus/dbus-memory.h \
  /usr/include/dbus-1.0/dbus/dbus-message.h \
  /usr/include/dbus-1.0/dbus/dbus-shared.h \
  /usr/include/dbus-1.0/dbus/dbus-pending-call.h \
  /usr/include/dbus-1.0/dbus/dbus-protocol.h \
  /usr/include/dbus-1.0/dbus/dbus-server.h \
  /usr/include/dbus-1.0/dbus/dbus-threads.h ../cbus/cbusconnection.h \
  ../cbus/cbusmonitor.h ../cbus/../common/fdnotifier.h \
  ../cbus/../common/timeout.h ../cbus/cbuserror.h ../cbus/cbusmessage.h \
  ../cbus/cbuspendingcall.h
cbusmessage.o: ../cbus/cbusmessage.cpp /usr/include/dbus-1.0/dbus/dbus.h \
  /usr/lib/dbus-1.0/include/dbus/dbus-arch-deps.h \
  /usr/include/dbus-1.0/dbus/dbus-macros.h \
  /usr/include/dbus-1.0/dbus/dbus-address.h \
  /usr/include/dbus-1.0/dbus/dbus-types.h \
  /usr/include/dbus-1.0/dbus/dbus-errors.h \
  /usr/include/dbus-1.0/dbus/dbus-bus.h \
  /usr/include/dbus-1.0/dbus/dbus-connection.h \
  /usr/include/dbus-1.0/dbus/dbus-memory.h \
  /usr/include/dbus-1.0/dbus/dbus-message.h \
  /usr/include/dbus-1.0/dbus/dbus-shared.h \
  /usr/include/dbus-1.0/dbus/dbus-pending-call.h \
  /usr/include/dbus-1.0/dbus/dbus-protocol.h \
  /usr/include/dbus-1.0/dbus/dbus-server.h \
  /usr/include/dbus-1.0/dbus/dbus-threads.h ../cbus/cbusmessage.h \
  ../cbus/cbuserror.h ../cbus/cbusconnection.h ../cbus/cbusmonitor.h \
  ../cbus/../common/fdnotifier.h /usr/include/sigc++-2.0/sigc++/sigc++.h \
  /usr/include/sigc++-2.0/sigc++/signal.h \
  /usr/include/sigc++-2.0/sigc++/signal_base.h \
  /usr/lib/sigc++-2.0/include/sigc++config.h \
  /usr/include/sigc++-2.0/sigc++/type_traits.h \
  /usr/include/sigc++-2.0/sigc++/reference_wrapper.h \
  /usr/include/sigc++-2.0/sigc++/trackable.h \
  /usr/include/sigc++-2.0/sigc++/functors/slot.h \
  /usr/include/sigc++-2.0/sigc++/visit_each.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/adaptor_trait.h \
  /usr/include/sigc++-2.0/sigc++/functors/functor_trait.h \
  /usr/include/sigc++-2.0/sigc++/functors/ptr_fun.h \
  /usr/include/sigc++-2.0/sigc++/functors/mem_fun.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/deduce_result_type.h \
  /usr/include/sigc++-2.0/sigc++/functors/slot_base.h \
  /usr/include/sigc++-2.0/sigc++/connection.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/adaptors.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/bind.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/bind_return.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/hide.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/retype_return.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/retype.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/compose.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/exception_catch.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/lambda.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/base.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/select.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/operator.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/group.h \
  /usr/include/sigc++-2.0/sigc++/functors/functors.h \
  ../cbus/../common/timeout.h ../cbus/cbuspendingcall.h \
  ../cbus/cbusfilter.h
cbusmonitor.o: ../cbus/cbusmonitor.cpp \
  /usr/include/sigc++-2.0/sigc++/sigc++.h \
  /usr/include/sigc++-2.0/sigc++/signal.h \
  /usr/include/sigc++-2.0/sigc++/signal_base.h \
  /usr/lib/sigc++-2.0/include/sigc++config.h \
  /usr/include/sigc++-2.0/sigc++/type_traits.h \
  /usr/include/sigc++-2.0/sigc++/reference_wrapper.h \
  /usr/include/sigc++-2.0/sigc++/trackable.h \
  /usr/include/sigc++-2.0/sigc++/functors/slot.h \
  /usr/include/sigc++-2.0/sigc++/visit_each.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/adaptor_trait.h \
  /usr/include/sigc++-2.0/sigc++/functors/functor_trait.h \
  /usr/include/sigc++-2.0/sigc++/functors/ptr_fun.h \
  /usr/include/sigc++-2.0/sigc++/functors/mem_fun.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/deduce_result_type.h \
  /usr/include/sigc++-2.0/sigc++/functors/slot_base.h \
  /usr/include/sigc++-2.0/sigc++/connection.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/adaptors.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/bind.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/bind_return.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/hide.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/retype_return.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/retype.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/compose.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/exception_catch.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/lambda.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/base.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/select.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/operator.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/group.h \
  /usr/include/sigc++-2.0/sigc++/functors/functors.h ../cbus/cbusdebug.h \
  ../cbus/../common/debug.h ../cbus/cbusmonitor.h \
  /usr/include/dbus-1.0/dbus/dbus.h \
  /usr/lib/dbus-1.0/include/dbus/dbus-arch-deps.h \
  /usr/include/dbus-1.0/dbus/dbus-macros.h \
  /usr/include/dbus-1.0/dbus/dbus-address.h \
  /usr/include/dbus-1.0/dbus/dbus-types.h \
  /usr/include/dbus-1.0/dbus/dbus-errors.h \
  /usr/include/dbus-1.0/dbus/dbus-bus.h \
  /usr/include/dbus-1.0/dbus/dbus-connection.h \
  /usr/include/dbus-1.0/dbus/dbus-memory.h \
  /usr/include/dbus-1.0/dbus/dbus-message.h \
  /usr/include/dbus-1.0/dbus/dbus-shared.h \
  /usr/include/dbus-1.0/dbus/dbus-pending-call.h \
  /usr/include/dbus-1.0/dbus/dbus-protocol.h \
  /usr/include/dbus-1.0/dbus/dbus-server.h \
  /usr/include/dbus-1.0/dbus/dbus-threads.h \
  ../cbus/../common/fdnotifier.h ../cbus/../common/timeout.h
cbusobject.o: ../cbus/cbusobject.cpp ../cbus/cbusdebug.h \
  ../cbus/../common/debug.h ../cbus/cbusobject.h ../cbus/cbusfilter.h \
  /usr/include/sigc++-2.0/sigc++/sigc++.h \
  /usr/include/sigc++-2.0/sigc++/signal.h \
  /usr/include/sigc++-2.0/sigc++/signal_base.h \
  /usr/lib/sigc++-2.0/include/sigc++config.h \
  /usr/include/sigc++-2.0/sigc++/type_traits.h \
  /usr/include/sigc++-2.0/sigc++/reference_wrapper.h \
  /usr/include/sigc++-2.0/sigc++/trackable.h \
  /usr/include/sigc++-2.0/sigc++/functors/slot.h \
  /usr/include/sigc++-2.0/sigc++/visit_each.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/adaptor_trait.h \
  /usr/include/sigc++-2.0/sigc++/functors/functor_trait.h \
  /usr/include/sigc++-2.0/sigc++/functors/ptr_fun.h \
  /usr/include/sigc++-2.0/sigc++/functors/mem_fun.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/deduce_result_type.h \
  /usr/include/sigc++-2.0/sigc++/functors/slot_base.h \
  /usr/include/sigc++-2.0/sigc++/connection.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/adaptors.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/bind.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/bind_return.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/hide.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/retype_return.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/retype.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/compose.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/exception_catch.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/lambda.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/base.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/select.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/operator.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/group.h \
  /usr/include/sigc++-2.0/sigc++/functors/functors.h \
  /usr/include/dbus-1.0/dbus/dbus.h \
  /usr/lib/dbus-1.0/include/dbus/dbus-arch-deps.h \
  /usr/include/dbus-1.0/dbus/dbus-macros.h \
  /usr/include/dbus-1.0/dbus/dbus-address.h \
  /usr/include/dbus-1.0/dbus/dbus-types.h \
  /usr/include/dbus-1.0/dbus/dbus-errors.h \
  /usr/include/dbus-1.0/dbus/dbus-bus.h \
  /usr/include/dbus-1.0/dbus/dbus-connection.h \
  /usr/include/dbus-1.0/dbus/dbus-memory.h \
  /usr/include/dbus-1.0/dbus/dbus-message.h \
  /usr/include/dbus-1.0/dbus/dbus-shared.h \
  /usr/include/dbus-1.0/dbus/dbus-pending-call.h \
  /usr/include/dbus-1.0/dbus/dbus-protocol.h \
  /usr/include/dbus-1.0/dbus/dbus-server.h \
  /usr/include/dbus-1.0/dbus/dbus-threads.h ../cbus/cbusconnection.h \
  ../cbus/cbusmonitor.h ../cbus/../common/fdnotifier.h \
  ../cbus/../common/timeout.h ../cbus/cbuserror.h ../cbus/cbusmessage.h \
  ../cbus/cbuspendingcall.h ../cbus/cbusinterface.h
cbuspendingcall.o: ../cbus/cbuspendingcall.cpp ../cbus/cbuspendingcall.h \
  /usr/include/sigc++-2.0/sigc++/sigc++.h \
  /usr/include/sigc++-2.0/sigc++/signal.h \
  /usr/include/sigc++-2.0/sigc++/signal_base.h \
  /usr/lib/sigc++-2.0/include/sigc++config.h \
  /usr/include/sigc++-2.0/sigc++/type_traits.h \
  /usr/include/sigc++-2.0/sigc++/reference_wrapper.h \
  /usr/include/sigc++-2.0/sigc++/trackable.h \
  /usr/include/sigc++-2.0/sigc++/functors/slot.h \
  /usr/include/sigc++-2.0/sigc++/visit_each.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/adaptor_trait.h \
  /usr/include/sigc++-2.0/sigc++/functors/functor_trait.h \
  /usr/include/sigc++-2.0/sigc++/functors/ptr_fun.h \
  /usr/include/sigc++-2.0/sigc++/functors/mem_fun.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/deduce_result_type.h \
  /usr/include/sigc++-2.0/sigc++/functors/slot_base.h \
  /usr/include/sigc++-2.0/sigc++/connection.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/adaptors.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/bind.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/bind_return.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/hide.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/retype_return.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/retype.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/compose.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/exception_catch.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/lambda.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/base.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/select.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/operator.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/group.h \
  /usr/include/sigc++-2.0/sigc++/functors/functors.h \
  /usr/include/dbus-1.0/dbus/dbus.h \
  /usr/lib/dbus-1.0/include/dbus/dbus-arch-deps.h \
  /usr/include/dbus-1.0/dbus/dbus-macros.h \
  /usr/include/dbus-1.0/dbus/dbus-address.h \
  /usr/include/dbus-1.0/dbus/dbus-types.h \
  /usr/include/dbus-1.0/dbus/dbus-errors.h \
  /usr/include/dbus-1.0/dbus/dbus-bus.h \
  /usr/include/dbus-1.0/dbus/dbus-connection.h \
  /usr/include/dbus-1.0/dbus/dbus-memory.h \
  /usr/include/dbus-1.0/dbus/dbus-message.h \
  /usr/include/dbus-1.0/dbus/dbus-shared.h \
  /usr/include/dbus-1.0/dbus/dbus-pending-call.h \
  /usr/include/dbus-1.0/dbus/dbus-protocol.h \
  /usr/include/dbus-1.0/dbus/dbus-server.h \
  /usr/include/dbus-1.0/dbus/dbus-threads.h ../cbus/cbusconnection.h \
  ../cbus/cbusmonitor.h ../cbus/../common/fdnotifier.h \
  ../cbus/../common/timeout.h ../cbus/cbuserror.h ../cbus/cbusmessage.h \
  ../cbus/cbusfilter.h
cbusserver.o: ../cbus/cbusserver.cpp ../cbus/cbusserver.h \
  ../cbus/../common/eventloop.h ../cbus/cbusmonitor.h \
  /usr/include/dbus-1.0/dbus/dbus.h \
  /usr/lib/dbus-1.0/include/dbus/dbus-arch-deps.h \
  /usr/include/dbus-1.0/dbus/dbus-macros.h \
  /usr/include/dbus-1.0/dbus/dbus-address.h \
  /usr/include/dbus-1.0/dbus/dbus-types.h \
  /usr/include/dbus-1.0/dbus/dbus-errors.h \
  /usr/include/dbus-1.0/dbus/dbus-bus.h \
  /usr/include/dbus-1.0/dbus/dbus-connection.h \
  /usr/include/dbus-1.0/dbus/dbus-memory.h \
  /usr/include/dbus-1.0/dbus/dbus-message.h \
  /usr/include/dbus-1.0/dbus/dbus-shared.h \
  /usr/include/dbus-1.0/dbus/dbus-pending-call.h \
  /usr/include/dbus-1.0/dbus/dbus-protocol.h \
  /usr/include/dbus-1.0/dbus/dbus-server.h \
  /usr/include/dbus-1.0/dbus/dbus-threads.h \
  ../cbus/../common/fdnotifier.h /usr/include/sigc++-2.0/sigc++/sigc++.h \
  /usr/include/sigc++-2.0/sigc++/signal.h \
  /usr/include/sigc++-2.0/sigc++/signal_base.h \
  /usr/lib/sigc++-2.0/include/sigc++config.h \
  /usr/include/sigc++-2.0/sigc++/type_traits.h \
  /usr/include/sigc++-2.0/sigc++/reference_wrapper.h \
  /usr/include/sigc++-2.0/sigc++/trackable.h \
  /usr/include/sigc++-2.0/sigc++/functors/slot.h \
  /usr/include/sigc++-2.0/sigc++/visit_each.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/adaptor_trait.h \
  /usr/include/sigc++-2.0/sigc++/functors/functor_trait.h \
  /usr/include/sigc++-2.0/sigc++/functors/ptr_fun.h \
  /usr/include/sigc++-2.0/sigc++/functors/mem_fun.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/deduce_result_type.h \
  /usr/include/sigc++-2.0/sigc++/functors/slot_base.h \
  /usr/include/sigc++-2.0/sigc++/connection.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/adaptors.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/bind.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/bind_return.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/hide.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/retype_return.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/retype.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/compose.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/exception_catch.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/lambda.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/base.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/select.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/operator.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/group.h \
  /usr/include/sigc++-2.0/sigc++/functors/functors.h \
  ../cbus/../common/timeout.h ../cbus/cbuserror.h ../cbus/cbusmessage.h \
  ../cbus/cbusconnection.h ../cbus/cbuspendingcall.h ../cbus/cbusfilter.h
cbusservice.o: ../cbus/cbusservice.cpp ../cbus/cbusservice.h \
  ../cbus/cbusconnection.h /usr/include/dbus-1.0/dbus/dbus.h \
  /usr/lib/dbus-1.0/include/dbus/dbus-arch-deps.h \
  /usr/include/dbus-1.0/dbus/dbus-macros.h \
  /usr/include/dbus-1.0/dbus/dbus-address.h \
  /usr/include/dbus-1.0/dbus/dbus-types.h \
  /usr/include/dbus-1.0/dbus/dbus-errors.h \
  /usr/include/dbus-1.0/dbus/dbus-bus.h \
  /usr/include/dbus-1.0/dbus/dbus-connection.h \
  /usr/include/dbus-1.0/dbus/dbus-memory.h \
  /usr/include/dbus-1.0/dbus/dbus-message.h \
  /usr/include/dbus-1.0/dbus/dbus-shared.h \
  /usr/include/dbus-1.0/dbus/dbus-pending-call.h \
  /usr/include/dbus-1.0/dbus/dbus-protocol.h \
  /usr/include/dbus-1.0/dbus/dbus-server.h \
  /usr/include/dbus-1.0/dbus/dbus-threads.h ../cbus/cbusmonitor.h \
  ../cbus/../common/fdnotifier.h /usr/include/sigc++-2.0/sigc++/sigc++.h \
  /usr/include/sigc++-2.0/sigc++/signal.h \
  /usr/include/sigc++-2.0/sigc++/signal_base.h \
  /usr/lib/sigc++-2.0/include/sigc++config.h \
  /usr/include/sigc++-2.0/sigc++/type_traits.h \
  /usr/include/sigc++-2.0/sigc++/reference_wrapper.h \
  /usr/include/sigc++-2.0/sigc++/trackable.h \
  /usr/include/sigc++-2.0/sigc++/functors/slot.h \
  /usr/include/sigc++-2.0/sigc++/visit_each.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/adaptor_trait.h \
  /usr/include/sigc++-2.0/sigc++/functors/functor_trait.h \
  /usr/include/sigc++-2.0/sigc++/functors/ptr_fun.h \
  /usr/include/sigc++-2.0/sigc++/functors/mem_fun.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/deduce_result_type.h \
  /usr/include/sigc++-2.0/sigc++/functors/slot_base.h \
  /usr/include/sigc++-2.0/sigc++/connection.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/adaptors.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/bind.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/bind_return.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/hide.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/retype_return.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/retype.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/compose.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/exception_catch.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/lambda.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/base.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/select.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/operator.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/group.h \
  /usr/include/sigc++-2.0/sigc++/functors/functors.h \
  ../cbus/../common/timeout.h ../cbus/cbuserror.h ../cbus/cbusmessage.h \
  ../cbus/cbuspendingcall.h ../cbus/cbusfilter.h ../cbus/cbusobject.h \
  ../cbus/cbusinterface.h
