#ifndef __BTOOL_HCI_TRACKER_H
#define __BTOOL_HCI_TRACKER_H

#include <map>

#include "../../cbus/cbus.h"

#include "../../hal/halmanager.h"
#include "../../hal/haldevice.h"

#include "../../libbluetool/hcidevice.h"

class HciTracker;
class HciManager;

#include "hci_device.h"

class HciTracker : public HalManager
{
public:
	HciTracker();
	
	~HciTracker();

private:
	/*	signals generated by the HalManager
	*/
	void DeviceAdded( const DBus::SignalMessage& );
	void DeviceRemoved( const DBus::SignalMessage& );

private:

	HciDevicePTable	_devices;

friend class HciManager;
};

#endif//__BTOOL_HCI_TRACKER_H
