cbusconnection.o: cbusconnection.cpp cbusdebug.h ../common/debug.h \
  cbusconnection.h /usr/include/dbus-1.0/dbus/dbus.h \
  /usr/lib/dbus-1.0/include/dbus/dbus-arch-deps.h \
  /usr/include/dbus-1.0/dbus/dbus-macros.h \
  /usr/include/dbus-1.0/dbus/dbus-address.h \
  /usr/include/dbus-1.0/dbus/dbus-types.h \
  /usr/include/dbus-1.0/dbus/dbus-errors.h \
  /usr/include/dbus-1.0/dbus/dbus-bus.h \
  /usr/include/dbus-1.0/dbus/dbus-connection.h \
  /usr/include/dbus-1.0/dbus/dbus-memory.h \
  /usr/include/dbus-1.0/dbus/dbus-message.h \
  /usr/include/dbus-1.0/dbus/dbus-shared.h \
  /usr/include/dbus-1.0/dbus/dbus-pending-call.h \
  /usr/include/dbus-1.0/dbus/dbus-protocol.h \
  /usr/include/dbus-1.0/dbus/dbus-server.h \
  /usr/include/dbus-1.0/dbus/dbus-threads.h cbusmonitor.h \
  ../common/fdnotifier.h /usr/include/sigc++-2.0/sigc++/sigc++.h \
  /usr/include/sigc++-2.0/sigc++/signal.h \
  /usr/include/sigc++-2.0/sigc++/signal_base.h \
  /usr/lib/sigc++-2.0/include/sigc++config.h \
  /usr/include/sigc++-2.0/sigc++/type_traits.h \
  /usr/include/sigc++-2.0/sigc++/reference_wrapper.h \
  /usr/include/sigc++-2.0/sigc++/trackable.h \
  /usr/include/sigc++-2.0/sigc++/functors/slot.h \
  /usr/include/sigc++-2.0/sigc++/visit_each.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/adaptor_trait.h \
  /usr/include/sigc++-2.0/sigc++/functors/functor_trait.h \
  /usr/include/sigc++-2.0/sigc++/functors/ptr_fun.h \
  /usr/include/sigc++-2.0/sigc++/functors/mem_fun.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/deduce_result_type.h \
  /usr/include/sigc++-2.0/sigc++/functors/slot_base.h \
  /usr/include/sigc++-2.0/sigc++/connection.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/adaptors.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/bind.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/bind_return.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/hide.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/retype_return.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/retype.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/compose.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/exception_catch.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/lambda.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/base.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/select.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/operator.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/group.h \
  /usr/include/sigc++-2.0/sigc++/functors/functors.h ../common/timeout.h \
  cbuserror.h cbusmessage.h cbuspendingcall.h cbusfilter.h
cbuserror.o: cbuserror.cpp cbusdebug.h ../common/debug.h cbuserror.h \
  /usr/include/dbus-1.0/dbus/dbus.h \
  /usr/lib/dbus-1.0/include/dbus/dbus-arch-deps.h \
  /usr/include/dbus-1.0/dbus/dbus-macros.h \
  /usr/include/dbus-1.0/dbus/dbus-address.h \
  /usr/include/dbus-1.0/dbus/dbus-types.h \
  /usr/include/dbus-1.0/dbus/dbus-errors.h \
  /usr/include/dbus-1.0/dbus/dbus-bus.h \
  /usr/include/dbus-1.0/dbus/dbus-connection.h \
  /usr/include/dbus-1.0/dbus/dbus-memory.h \
  /usr/include/dbus-1.0/dbus/dbus-message.h \
  /usr/include/dbus-1.0/dbus/dbus-shared.h \
  /usr/include/dbus-1.0/dbus/dbus-pending-call.h \
  /usr/include/dbus-1.0/dbus/dbus-protocol.h \
  /usr/include/dbus-1.0/dbus/dbus-server.h \
  /usr/include/dbus-1.0/dbus/dbus-threads.h cbusmessage.h \
  cbusconnection.h cbusmonitor.h ../common/fdnotifier.h \
  /usr/include/sigc++-2.0/sigc++/sigc++.h \
  /usr/include/sigc++-2.0/sigc++/signal.h \
  /usr/include/sigc++-2.0/sigc++/signal_base.h \
  /usr/lib/sigc++-2.0/include/sigc++config.h \
  /usr/include/sigc++-2.0/sigc++/type_traits.h \
  /usr/include/sigc++-2.0/sigc++/reference_wrapper.h \
  /usr/include/sigc++-2.0/sigc++/trackable.h \
  /usr/include/sigc++-2.0/sigc++/functors/slot.h \
  /usr/include/sigc++-2.0/sigc++/visit_each.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/adaptor_trait.h \
  /usr/include/sigc++-2.0/sigc++/functors/functor_trait.h \
  /usr/include/sigc++-2.0/sigc++/functors/ptr_fun.h \
  /usr/include/sigc++-2.0/sigc++/functors/mem_fun.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/deduce_result_type.h \
  /usr/include/sigc++-2.0/sigc++/functors/slot_base.h \
  /usr/include/sigc++-2.0/sigc++/connection.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/adaptors.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/bind.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/bind_return.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/hide.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/retype_return.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/retype.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/compose.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/exception_catch.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/lambda.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/base.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/select.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/operator.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/group.h \
  /usr/include/sigc++-2.0/sigc++/functors/functors.h ../common/timeout.h \
  cbuspendingcall.h cbusfilter.h
cbusinterface.o: cbusinterface.cpp cbusdebug.h ../common/debug.h \
  cbusinterface.h /usr/include/sigc++-2.0/sigc++/sigc++.h \
  /usr/include/sigc++-2.0/sigc++/signal.h \
  /usr/include/sigc++-2.0/sigc++/signal_base.h \
  /usr/lib/sigc++-2.0/include/sigc++config.h \
  /usr/include/sigc++-2.0/sigc++/type_traits.h \
  /usr/include/sigc++-2.0/sigc++/reference_wrapper.h \
  /usr/include/sigc++-2.0/sigc++/trackable.h \
  /usr/include/sigc++-2.0/sigc++/functors/slot.h \
  /usr/include/sigc++-2.0/sigc++/visit_each.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/adaptor_trait.h \
  /usr/include/sigc++-2.0/sigc++/functors/functor_trait.h \
  /usr/include/sigc++-2.0/sigc++/functors/ptr_fun.h \
  /usr/include/sigc++-2.0/sigc++/functors/mem_fun.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/deduce_result_type.h \
  /usr/include/sigc++-2.0/sigc++/functors/slot_base.h \
  /usr/include/sigc++-2.0/sigc++/connection.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/adaptors.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/bind.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/bind_return.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/hide.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/retype_return.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/retype.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/compose.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/exception_catch.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/lambda.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/base.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/select.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/operator.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/group.h \
  /usr/include/sigc++-2.0/sigc++/functors/functors.h cbusobject.h \
  cbusfilter.h /usr/include/dbus-1.0/dbus/dbus.h \
  /usr/lib/dbus-1.0/include/dbus/dbus-arch-deps.h \
  /usr/include/dbus-1.0/dbus/dbus-macros.h \
  /usr/include/dbus-1.0/dbus/dbus-address.h \
  /usr/include/dbus-1.0/dbus/dbus-types.h \
  /usr/include/dbus-1.0/dbus/dbus-errors.h \
  /usr/include/dbus-1.0/dbus/dbus-bus.h \
  /usr/include/dbus-1.0/dbus/dbus-connection.h \
  /usr/include/dbus-1.0/dbus/dbus-memory.h \
  /usr/include/dbus-1.0/dbus/dbus-message.h \
  /usr/include/dbus-1.0/dbus/dbus-shared.h \
  /usr/include/dbus-1.0/dbus/dbus-pending-call.h \
  /usr/include/dbus-1.0/dbus/dbus-protocol.h \
  /usr/include/dbus-1.0/dbus/dbus-server.h \
  /usr/include/dbus-1.0/dbus/dbus-threads.h cbusconnection.h \
  cbusmonitor.h ../common/fdnotifier.h ../common/timeout.h cbuserror.h \
  cbusmessage.h cbuspendingcall.h
cbusmessage.o: cbusmessage.cpp /usr/include/dbus-1.0/dbus/dbus.h \
  /usr/lib/dbus-1.0/include/dbus/dbus-arch-deps.h \
  /usr/include/dbus-1.0/dbus/dbus-macros.h \
  /usr/include/dbus-1.0/dbus/dbus-address.h \
  /usr/include/dbus-1.0/dbus/dbus-types.h \
  /usr/include/dbus-1.0/dbus/dbus-errors.h \
  /usr/include/dbus-1.0/dbus/dbus-bus.h \
  /usr/include/dbus-1.0/dbus/dbus-connection.h \
  /usr/include/dbus-1.0/dbus/dbus-memory.h \
  /usr/include/dbus-1.0/dbus/dbus-message.h \
  /usr/include/dbus-1.0/dbus/dbus-shared.h \
  /usr/include/dbus-1.0/dbus/dbus-pending-call.h \
  /usr/include/dbus-1.0/dbus/dbus-protocol.h \
  /usr/include/dbus-1.0/dbus/dbus-server.h \
  /usr/include/dbus-1.0/dbus/dbus-threads.h cbusmessage.h cbuserror.h \
  cbusconnection.h cbusmonitor.h ../common/fdnotifier.h \
  /usr/include/sigc++-2.0/sigc++/sigc++.h \
  /usr/include/sigc++-2.0/sigc++/signal.h \
  /usr/include/sigc++-2.0/sigc++/signal_base.h \
  /usr/lib/sigc++-2.0/include/sigc++config.h \
  /usr/include/sigc++-2.0/sigc++/type_traits.h \
  /usr/include/sigc++-2.0/sigc++/reference_wrapper.h \
  /usr/include/sigc++-2.0/sigc++/trackable.h \
  /usr/include/sigc++-2.0/sigc++/functors/slot.h \
  /usr/include/sigc++-2.0/sigc++/visit_each.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/adaptor_trait.h \
  /usr/include/sigc++-2.0/sigc++/functors/functor_trait.h \
  /usr/include/sigc++-2.0/sigc++/functors/ptr_fun.h \
  /usr/include/sigc++-2.0/sigc++/functors/mem_fun.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/deduce_result_type.h \
  /usr/include/sigc++-2.0/sigc++/functors/slot_base.h \
  /usr/include/sigc++-2.0/sigc++/connection.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/adaptors.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/bind.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/bind_return.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/hide.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/retype_return.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/retype.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/compose.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/exception_catch.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/lambda.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/base.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/select.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/operator.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/group.h \
  /usr/include/sigc++-2.0/sigc++/functors/functors.h ../common/timeout.h \
  cbuspendingcall.h cbusfilter.h
cbusmonitor.o: cbusmonitor.cpp /usr/include/sigc++-2.0/sigc++/sigc++.h \
  /usr/include/sigc++-2.0/sigc++/signal.h \
  /usr/include/sigc++-2.0/sigc++/signal_base.h \
  /usr/lib/sigc++-2.0/include/sigc++config.h \
  /usr/include/sigc++-2.0/sigc++/type_traits.h \
  /usr/include/sigc++-2.0/sigc++/reference_wrapper.h \
  /usr/include/sigc++-2.0/sigc++/trackable.h \
  /usr/include/sigc++-2.0/sigc++/functors/slot.h \
  /usr/include/sigc++-2.0/sigc++/visit_each.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/adaptor_trait.h \
  /usr/include/sigc++-2.0/sigc++/functors/functor_trait.h \
  /usr/include/sigc++-2.0/sigc++/functors/ptr_fun.h \
  /usr/include/sigc++-2.0/sigc++/functors/mem_fun.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/deduce_result_type.h \
  /usr/include/sigc++-2.0/sigc++/functors/slot_base.h \
  /usr/include/sigc++-2.0/sigc++/connection.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/adaptors.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/bind.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/bind_return.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/hide.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/retype_return.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/retype.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/compose.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/exception_catch.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/lambda.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/base.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/select.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/operator.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/group.h \
  /usr/include/sigc++-2.0/sigc++/functors/functors.h cbusdebug.h \
  ../common/debug.h cbusmonitor.h /usr/include/dbus-1.0/dbus/dbus.h \
  /usr/lib/dbus-1.0/include/dbus/dbus-arch-deps.h \
  /usr/include/dbus-1.0/dbus/dbus-macros.h \
  /usr/include/dbus-1.0/dbus/dbus-address.h \
  /usr/include/dbus-1.0/dbus/dbus-types.h \
  /usr/include/dbus-1.0/dbus/dbus-errors.h \
  /usr/include/dbus-1.0/dbus/dbus-bus.h \
  /usr/include/dbus-1.0/dbus/dbus-connection.h \
  /usr/include/dbus-1.0/dbus/dbus-memory.h \
  /usr/include/dbus-1.0/dbus/dbus-message.h \
  /usr/include/dbus-1.0/dbus/dbus-shared.h \
  /usr/include/dbus-1.0/dbus/dbus-pending-call.h \
  /usr/include/dbus-1.0/dbus/dbus-protocol.h \
  /usr/include/dbus-1.0/dbus/dbus-server.h \
  /usr/include/dbus-1.0/dbus/dbus-threads.h ../common/fdnotifier.h \
  ../common/timeout.h
cbusobject.o: cbusobject.cpp cbusdebug.h ../common/debug.h cbusobject.h \
  cbusfilter.h /usr/include/sigc++-2.0/sigc++/sigc++.h \
  /usr/include/sigc++-2.0/sigc++/signal.h \
  /usr/include/sigc++-2.0/sigc++/signal_base.h \
  /usr/lib/sigc++-2.0/include/sigc++config.h \
  /usr/include/sigc++-2.0/sigc++/type_traits.h \
  /usr/include/sigc++-2.0/sigc++/reference_wrapper.h \
  /usr/include/sigc++-2.0/sigc++/trackable.h \
  /usr/include/sigc++-2.0/sigc++/functors/slot.h \
  /usr/include/sigc++-2.0/sigc++/visit_each.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/adaptor_trait.h \
  /usr/include/sigc++-2.0/sigc++/functors/functor_trait.h \
  /usr/include/sigc++-2.0/sigc++/functors/ptr_fun.h \
  /usr/include/sigc++-2.0/sigc++/functors/mem_fun.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/deduce_result_type.h \
  /usr/include/sigc++-2.0/sigc++/functors/slot_base.h \
  /usr/include/sigc++-2.0/sigc++/connection.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/adaptors.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/bind.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/bind_return.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/hide.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/retype_return.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/retype.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/compose.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/exception_catch.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/lambda.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/base.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/select.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/operator.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/group.h \
  /usr/include/sigc++-2.0/sigc++/functors/functors.h \
  /usr/include/dbus-1.0/dbus/dbus.h \
  /usr/lib/dbus-1.0/include/dbus/dbus-arch-deps.h \
  /usr/include/dbus-1.0/dbus/dbus-macros.h \
  /usr/include/dbus-1.0/dbus/dbus-address.h \
  /usr/include/dbus-1.0/dbus/dbus-types.h \
  /usr/include/dbus-1.0/dbus/dbus-errors.h \
  /usr/include/dbus-1.0/dbus/dbus-bus.h \
  /usr/include/dbus-1.0/dbus/dbus-connection.h \
  /usr/include/dbus-1.0/dbus/dbus-memory.h \
  /usr/include/dbus-1.0/dbus/dbus-message.h \
  /usr/include/dbus-1.0/dbus/dbus-shared.h \
  /usr/include/dbus-1.0/dbus/dbus-pending-call.h \
  /usr/include/dbus-1.0/dbus/dbus-protocol.h \
  /usr/include/dbus-1.0/dbus/dbus-server.h \
  /usr/include/dbus-1.0/dbus/dbus-threads.h cbusconnection.h \
  cbusmonitor.h ../common/fdnotifier.h ../common/timeout.h cbuserror.h \
  cbusmessage.h cbuspendingcall.h cbusinterface.h
cbuspendingcall.o: cbuspendingcall.cpp cbuspendingcall.h \
  /usr/include/sigc++-2.0/sigc++/sigc++.h \
  /usr/include/sigc++-2.0/sigc++/signal.h \
  /usr/include/sigc++-2.0/sigc++/signal_base.h \
  /usr/lib/sigc++-2.0/include/sigc++config.h \
  /usr/include/sigc++-2.0/sigc++/type_traits.h \
  /usr/include/sigc++-2.0/sigc++/reference_wrapper.h \
  /usr/include/sigc++-2.0/sigc++/trackable.h \
  /usr/include/sigc++-2.0/sigc++/functors/slot.h \
  /usr/include/sigc++-2.0/sigc++/visit_each.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/adaptor_trait.h \
  /usr/include/sigc++-2.0/sigc++/functors/functor_trait.h \
  /usr/include/sigc++-2.0/sigc++/functors/ptr_fun.h \
  /usr/include/sigc++-2.0/sigc++/functors/mem_fun.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/deduce_result_type.h \
  /usr/include/sigc++-2.0/sigc++/functors/slot_base.h \
  /usr/include/sigc++-2.0/sigc++/connection.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/adaptors.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/bind.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/bind_return.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/hide.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/retype_return.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/retype.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/compose.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/exception_catch.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/lambda.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/base.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/select.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/operator.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/group.h \
  /usr/include/sigc++-2.0/sigc++/functors/functors.h \
  /usr/include/dbus-1.0/dbus/dbus.h \
  /usr/lib/dbus-1.0/include/dbus/dbus-arch-deps.h \
  /usr/include/dbus-1.0/dbus/dbus-macros.h \
  /usr/include/dbus-1.0/dbus/dbus-address.h \
  /usr/include/dbus-1.0/dbus/dbus-types.h \
  /usr/include/dbus-1.0/dbus/dbus-errors.h \
  /usr/include/dbus-1.0/dbus/dbus-bus.h \
  /usr/include/dbus-1.0/dbus/dbus-connection.h \
  /usr/include/dbus-1.0/dbus/dbus-memory.h \
  /usr/include/dbus-1.0/dbus/dbus-message.h \
  /usr/include/dbus-1.0/dbus/dbus-shared.h \
  /usr/include/dbus-1.0/dbus/dbus-pending-call.h \
  /usr/include/dbus-1.0/dbus/dbus-protocol.h \
  /usr/include/dbus-1.0/dbus/dbus-server.h \
  /usr/include/dbus-1.0/dbus/dbus-threads.h cbusconnection.h \
  cbusmonitor.h ../common/fdnotifier.h ../common/timeout.h cbuserror.h \
  cbusmessage.h cbusfilter.h
cbusserver.o: cbusserver.cpp cbusserver.h ../common/eventloop.h \
  cbusmonitor.h /usr/include/dbus-1.0/dbus/dbus.h \
  /usr/lib/dbus-1.0/include/dbus/dbus-arch-deps.h \
  /usr/include/dbus-1.0/dbus/dbus-macros.h \
  /usr/include/dbus-1.0/dbus/dbus-address.h \
  /usr/include/dbus-1.0/dbus/dbus-types.h \
  /usr/include/dbus-1.0/dbus/dbus-errors.h \
  /usr/include/dbus-1.0/dbus/dbus-bus.h \
  /usr/include/dbus-1.0/dbus/dbus-connection.h \
  /usr/include/dbus-1.0/dbus/dbus-memory.h \
  /usr/include/dbus-1.0/dbus/dbus-message.h \
  /usr/include/dbus-1.0/dbus/dbus-shared.h \
  /usr/include/dbus-1.0/dbus/dbus-pending-call.h \
  /usr/include/dbus-1.0/dbus/dbus-protocol.h \
  /usr/include/dbus-1.0/dbus/dbus-server.h \
  /usr/include/dbus-1.0/dbus/dbus-threads.h ../common/fdnotifier.h \
  /usr/include/sigc++-2.0/sigc++/sigc++.h \
  /usr/include/sigc++-2.0/sigc++/signal.h \
  /usr/include/sigc++-2.0/sigc++/signal_base.h \
  /usr/lib/sigc++-2.0/include/sigc++config.h \
  /usr/include/sigc++-2.0/sigc++/type_traits.h \
  /usr/include/sigc++-2.0/sigc++/reference_wrapper.h \
  /usr/include/sigc++-2.0/sigc++/trackable.h \
  /usr/include/sigc++-2.0/sigc++/functors/slot.h \
  /usr/include/sigc++-2.0/sigc++/visit_each.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/adaptor_trait.h \
  /usr/include/sigc++-2.0/sigc++/functors/functor_trait.h \
  /usr/include/sigc++-2.0/sigc++/functors/ptr_fun.h \
  /usr/include/sigc++-2.0/sigc++/functors/mem_fun.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/deduce_result_type.h \
  /usr/include/sigc++-2.0/sigc++/functors/slot_base.h \
  /usr/include/sigc++-2.0/sigc++/connection.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/adaptors.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/bind.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/bind_return.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/hide.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/retype_return.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/retype.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/compose.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/exception_catch.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/lambda.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/base.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/select.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/operator.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/group.h \
  /usr/include/sigc++-2.0/sigc++/functors/functors.h ../common/timeout.h \
  cbuserror.h cbusmessage.h cbusconnection.h cbuspendingcall.h \
  cbusfilter.h
cbusservice.o: cbusservice.cpp cbusservice.h cbusconnection.h \
  /usr/include/dbus-1.0/dbus/dbus.h \
  /usr/lib/dbus-1.0/include/dbus/dbus-arch-deps.h \
  /usr/include/dbus-1.0/dbus/dbus-macros.h \
  /usr/include/dbus-1.0/dbus/dbus-address.h \
  /usr/include/dbus-1.0/dbus/dbus-types.h \
  /usr/include/dbus-1.0/dbus/dbus-errors.h \
  /usr/include/dbus-1.0/dbus/dbus-bus.h \
  /usr/include/dbus-1.0/dbus/dbus-connection.h \
  /usr/include/dbus-1.0/dbus/dbus-memory.h \
  /usr/include/dbus-1.0/dbus/dbus-message.h \
  /usr/include/dbus-1.0/dbus/dbus-shared.h \
  /usr/include/dbus-1.0/dbus/dbus-pending-call.h \
  /usr/include/dbus-1.0/dbus/dbus-protocol.h \
  /usr/include/dbus-1.0/dbus/dbus-server.h \
  /usr/include/dbus-1.0/dbus/dbus-threads.h cbusmonitor.h \
  ../common/fdnotifier.h /usr/include/sigc++-2.0/sigc++/sigc++.h \
  /usr/include/sigc++-2.0/sigc++/signal.h \
  /usr/include/sigc++-2.0/sigc++/signal_base.h \
  /usr/lib/sigc++-2.0/include/sigc++config.h \
  /usr/include/sigc++-2.0/sigc++/type_traits.h \
  /usr/include/sigc++-2.0/sigc++/reference_wrapper.h \
  /usr/include/sigc++-2.0/sigc++/trackable.h \
  /usr/include/sigc++-2.0/sigc++/functors/slot.h \
  /usr/include/sigc++-2.0/sigc++/visit_each.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/adaptor_trait.h \
  /usr/include/sigc++-2.0/sigc++/functors/functor_trait.h \
  /usr/include/sigc++-2.0/sigc++/functors/ptr_fun.h \
  /usr/include/sigc++-2.0/sigc++/functors/mem_fun.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/deduce_result_type.h \
  /usr/include/sigc++-2.0/sigc++/functors/slot_base.h \
  /usr/include/sigc++-2.0/sigc++/connection.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/adaptors.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/bind.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/bind_return.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/hide.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/retype_return.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/retype.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/compose.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/exception_catch.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/lambda.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/base.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/select.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/operator.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/group.h \
  /usr/include/sigc++-2.0/sigc++/functors/functors.h ../common/timeout.h \
  cbuserror.h cbusmessage.h cbuspendingcall.h cbusfilter.h cbusobject.h \
  cbusinterface.h
eventloop.o: ../common/eventloop.cpp ../common/debug.h \
  ../common/eventloop.h ../common/timeout.h \
  /usr/include/sigc++-2.0/sigc++/sigc++.h \
  /usr/include/sigc++-2.0/sigc++/signal.h \
  /usr/include/sigc++-2.0/sigc++/signal_base.h \
  /usr/lib/sigc++-2.0/include/sigc++config.h \
  /usr/include/sigc++-2.0/sigc++/type_traits.h \
  /usr/include/sigc++-2.0/sigc++/reference_wrapper.h \
  /usr/include/sigc++-2.0/sigc++/trackable.h \
  /usr/include/sigc++-2.0/sigc++/functors/slot.h \
  /usr/include/sigc++-2.0/sigc++/visit_each.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/adaptor_trait.h \
  /usr/include/sigc++-2.0/sigc++/functors/functor_trait.h \
  /usr/include/sigc++-2.0/sigc++/functors/ptr_fun.h \
  /usr/include/sigc++-2.0/sigc++/functors/mem_fun.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/deduce_result_type.h \
  /usr/include/sigc++-2.0/sigc++/functors/slot_base.h \
  /usr/include/sigc++-2.0/sigc++/connection.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/adaptors.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/bind.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/bind_return.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/hide.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/retype_return.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/retype.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/compose.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/exception_catch.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/lambda.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/base.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/select.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/operator.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/group.h \
  /usr/include/sigc++-2.0/sigc++/functors/functors.h \
  ../common/fdnotifier.h
fdnotifier.o: ../common/fdnotifier.cpp ../common/fdnotifier.h \
  /usr/include/sigc++-2.0/sigc++/sigc++.h \
  /usr/include/sigc++-2.0/sigc++/signal.h \
  /usr/include/sigc++-2.0/sigc++/signal_base.h \
  /usr/lib/sigc++-2.0/include/sigc++config.h \
  /usr/include/sigc++-2.0/sigc++/type_traits.h \
  /usr/include/sigc++-2.0/sigc++/reference_wrapper.h \
  /usr/include/sigc++-2.0/sigc++/trackable.h \
  /usr/include/sigc++-2.0/sigc++/functors/slot.h \
  /usr/include/sigc++-2.0/sigc++/visit_each.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/adaptor_trait.h \
  /usr/include/sigc++-2.0/sigc++/functors/functor_trait.h \
  /usr/include/sigc++-2.0/sigc++/functors/ptr_fun.h \
  /usr/include/sigc++-2.0/sigc++/functors/mem_fun.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/deduce_result_type.h \
  /usr/include/sigc++-2.0/sigc++/functors/slot_base.h \
  /usr/include/sigc++-2.0/sigc++/connection.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/adaptors.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/bind.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/bind_return.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/hide.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/retype_return.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/retype.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/compose.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/exception_catch.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/lambda.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/base.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/select.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/operator.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/group.h \
  /usr/include/sigc++-2.0/sigc++/functors/functors.h
timeout.o: ../common/timeout.cpp ../common/timeout.h \
  /usr/include/sigc++-2.0/sigc++/sigc++.h \
  /usr/include/sigc++-2.0/sigc++/signal.h \
  /usr/include/sigc++-2.0/sigc++/signal_base.h \
  /usr/lib/sigc++-2.0/include/sigc++config.h \
  /usr/include/sigc++-2.0/sigc++/type_traits.h \
  /usr/include/sigc++-2.0/sigc++/reference_wrapper.h \
  /usr/include/sigc++-2.0/sigc++/trackable.h \
  /usr/include/sigc++-2.0/sigc++/functors/slot.h \
  /usr/include/sigc++-2.0/sigc++/visit_each.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/adaptor_trait.h \
  /usr/include/sigc++-2.0/sigc++/functors/functor_trait.h \
  /usr/include/sigc++-2.0/sigc++/functors/ptr_fun.h \
  /usr/include/sigc++-2.0/sigc++/functors/mem_fun.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/deduce_result_type.h \
  /usr/include/sigc++-2.0/sigc++/functors/slot_base.h \
  /usr/include/sigc++-2.0/sigc++/connection.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/adaptors.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/bind.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/bind_return.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/hide.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/retype_return.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/retype.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/compose.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/exception_catch.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/lambda.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/base.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/select.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/operator.h \
  /usr/include/sigc++-2.0/sigc++/adaptors/lambda/group.h \
  /usr/include/sigc++-2.0/sigc++/functors/functors.h
